### ISSUE TITLE
Add other options for opening the drawer

### ISSUE THREAD

**Issue by ColtonIdle** [alorma/Compose-Debug-Drawer#10]
Opening the drawer is a bit of a pain when using edge to edge navigation on a device.

Hyperion allows shake to open:
https://github.com/willowtreeapps/Hyperion-Android

Telescope has a clever technique of a two-finger hold (finger count is adjustable)
https://github.com/mattprecious/telescope

Another idea is a double-click (or triple-click) anywhere on the app open the drawer.

**Comment by alorma** [comment]
Thanks for your feedback.

Any idea on how to implement those features? I will investigate that and come back with a response.

(also, it's the same problem that we have on current drawer (from left)

**Comment by ColtonIdle** [comment]
Shake to open and two finger hold seems like we can borrow easily from those repos I linked. I think one of the coolest ones is a double click which it should be easy to intercept events but let them pass through since DebugDrawerLayout is already at the root.

**Comment by alorma** [comment]
Hi @ColtonIdle 

I just released new version `1.0.0-beta01.lib-02` with support for shake to open / close drawer. 

Can you try it?

**Comment by alorma** [comment]
Shake is enabled by default
