### ISSUE TITLE
Reduce minSdkVersion to 21

### ISSUE THREAD

**Issue by kyhule** [alorma/Compose-Debug-Drawer#13]
Is there anything being used by this library that requires minSdkVersion be set to 23? I cloned the library and set all to 21 and seemed to compile and sample app ran just fine. 

I was super excited to give this a try in a new project and I got it all integrated only to find out it had minSdkVersion 23.

**Comment by alorma** [comment]
Hi @kyhule .

Can you open a Pull request reducing minSDK to 21? I will merge it and do a new release
