### ISSUE TITLE
Breaks accessibility features

### ISSUE THREAD

**Issue by nimaeskandary** [alorma/Compose-Debug-Drawer#16]
It seems that the debug drawer component breaks talk back because the drawer and its slider sit above the app content. Talk back can only see app content on the leftmost sliver of the screen, but things to the right get cut off:

![2021-06-09 10 51 23](https://user-images.githubusercontent.com/9893183/121392775-ae462800-c91d-11eb-9a14-169f94ce103e.gif)

A potential fix is making the debug drawer content only render if the drawer is set to open, e.g. adding a conditional [here](https://github.com/alorma/Compose-Debug-Drawer/blob/main/drawer-base/src/main/java/com/alorma/drawer_base/DebugDrawer.kt#L199)

```
if (debugDrawerState.isOpen) {
    MaterialTheme(... rest of debug drawer
}
```

![2021-06-09 10 49 53](https://user-images.githubusercontent.com/9893183/121393227-26ace900-c91e-11eb-984a-51161ce7f31d.gif)

**Comment by alorma** [comment]
Hi @nimaeskandary !

Thanks for reporting it, I will take a look at it as soon as possible.

By the way, how to enable talkback? So I can properly test it?

**Comment by Kusand** [comment]
There's a couple of ways depending on your device. Most Android devices can follow [these suggestions](https://support.google.com/accessibility/android/answer/6007100?hl=en), but if you have a Samsung Galaxy device there's also [this list](https://www.samsung.com/ph/support/mobile-devices/how-to-customize-accessibility-settings-on-your-galaxy-phone/).

**Comment by alorma** [comment]
Thanks, will try with emulator, if not works will check with device.

Thanks

**Comment by alorma** [comment]
Hi @nimaeskandary 

Does it happens also with `Scaffold.drawerContent`?

I've checked that the swipe is from almost all screen, same way as DebugDrawer, and is something that maybe compose drawer has the same problem...

**Comment by nimaeskandary** [comment]
Hey @alorma thanks for looking into this, the emulators don't have talkback by default so I manually install the apk from https://apkpure.com/android-accessibility-suite/com.google.android.marvin.talkback then drag it into the emulator screen

I'll checkout `Scaffold.drawerContent` and see if there's a similar problem
