### ISSUE TITLE
POM incorrectly references Compose Settings project

### ISSUE THREAD

**Issue by kyhule** [alorma/Compose-Debug-Drawer#18]
https://github.com/alorma/Compose-Debug-Drawer/blob/13f241e84c479b7e85d4d662b8156973e9676dcb/scripts/publish-module.gradle#L43-L65

**Comment by alorma** [comment]
Ooooohps

Problems of copy paste!

Thanks for reporting @kyhule . I will release a version with compose rc02 and fix this thanks
